import { describe, expect, test } from "bun:test";
import {
  buildCommitArgv,
  buildPrCreateArgv,
  buildPushArgv,
  buildStageAllArgv,
  buildSuccessLabelArgv,
  defaultAutorunRemote,
  defaultAutorunSuccessLabel,
  formatCommitMessage,
  formatPrBody,
} from "./publish.ts";
import { formatAttemptMetadata } from "./attempts.ts";
import type { VerificationResult } from "./verification.ts";

const okVerification: VerificationResult = {
  ok: true,
  command: "bun run typecheck",
  exitCode: 0,
  stdout: "",
  stderr: "",
};

const failedVerification: VerificationResult = {
  ok: false,
  command: "bun run typecheck",
  exitCode: 2,
  stdout: "",
  stderr: "errors",
};

describe("autorun publish defaults", () => {
  test("default success label is roark-pr-opened", () => {
    expect(defaultAutorunSuccessLabel).toBe("roark-pr-opened");
  });

  test("default remote is origin", () => {
    expect(defaultAutorunRemote).toBe("origin");
  });
});

describe("autorun publish argv builders", () => {
  test("buildStageAllArgv stages all changes", () => {
    expect(buildStageAllArgv()).toEqual(["git", "add", "-A"]);
  });

  test("buildCommitArgv composes a git commit command", () => {
    expect(buildCommitArgv({ message: "roark: workflow artifacts for #9" })).toEqual([
      "git",
      "commit",
      "-m",
      "roark: workflow artifacts for #9",
    ]);
  });

  test("buildPushArgv composes a git push command with -u", () => {
    expect(buildPushArgv({ remote: "origin", branchName: "roark/issue-9" })).toEqual([
      "git",
      "push",
      "-u",
      "origin",
      "roark/issue-9",
    ]);
  });

  test("buildPrCreateArgv produces a draft gh pr create command with --repo", () => {
    expect(
      buildPrCreateArgv({
        repo: "owner/repo",
        baseBranch: "main",
        branchName: "roark/issue-9",
        title: "Fix bug",
        body: "Closes #9\n",
      }),
    ).toEqual([
      "gh",
      "pr",
      "create",
      "--draft",
      "--base",
      "main",
      "--head",
      "roark/issue-9",
      "--title",
      "Fix bug",
      "--body",
      "Closes #9\n",
      "--repo",
      "owner/repo",
    ]);
  });

  test("buildPrCreateArgv omits --repo when not provided", () => {
    expect(
      buildPrCreateArgv({
        baseBranch: "main",
        branchName: "roark/issue-9",
        title: "Fix bug",
        body: "Closes #9\n",
      }),
    ).toEqual([
      "gh",
      "pr",
      "create",
      "--draft",
      "--base",
      "main",
      "--head",
      "roark/issue-9",
      "--title",
      "Fix bug",
      "--body",
      "Closes #9\n",
    ]);
  });

  test("buildSuccessLabelArgv composes a gh issue edit command", () => {
    expect(
      buildSuccessLabelArgv({ issueNumber: 9, label: "roark-pr-opened", repo: "owner/repo" }),
    ).toEqual([
      "gh",
      "issue",
      "edit",
      "9",
      "--add-label",
      "roark-pr-opened",
      "--repo",
      "owner/repo",
    ]);
  });

  test("buildSuccessLabelArgv omits --repo when not provided", () => {
    expect(buildSuccessLabelArgv({ issueNumber: 9, label: "roark-pr-opened" })).toEqual([
      "gh",
      "issue",
      "edit",
      "9",
      "--add-label",
      "roark-pr-opened",
    ]);
  });
});

describe("formatCommitMessage", () => {
  test("includes the issue number", () => {
    expect(formatCommitMessage({ issueNumber: 9 })).toBe("roark: workflow artifacts for #9");
  });
});

describe("formatPrBody", () => {
  test("includes Closes, verification details, and artifact list when verification passed", () => {
    const body = formatPrBody({
      issueNumber: 9,
      verification: okVerification,
      runDirRelative: ".roark/runs/issue/9",
      artifactPaths: [
        ".roark/runs/issue/9/readiness.md",
        ".roark/runs/issue/9/verification.md",
        ".roark/runs/issue/9/implementation-plan.md",
      ],
    });

    expect(body).toContain("Closes #9");
    expect(body).toContain("## Verification");
    expect(body).toContain("- Command: `bun run typecheck`");
    expect(body).toContain("- Exit code: 0");
    expect(body).toContain("- Status: passed");
    expect(body).toContain("## Workflow artifacts");
    expect(body).toContain("- `.roark/runs/issue/9/readiness.md`");
    expect(body).toContain("- `.roark/runs/issue/9/verification.md`");
    expect(body).toContain("- `.roark/runs/issue/9/implementation-plan.md`");
    expect(body).toContain("Generated by roark autorun.");
  });

  test("reports failed verification status and exit code", () => {
    const body = formatPrBody({
      issueNumber: 9,
      verification: failedVerification,
      runDirRelative: ".roark/runs/issue/9",
      artifactPaths: [".roark/runs/issue/9/verification.md"],
    });

    expect(body).toContain("- Exit code: 2");
    expect(body).toContain("- Status: failed");
  });

  test("handles missing verification defensively", () => {
    const body = formatPrBody({
      issueNumber: 9,
      runDirRelative: ".roark/runs/issue/9",
      artifactPaths: [".roark/runs/issue/9/readiness.md"],
    });

    expect(body).toContain("Closes #9");
    expect(body).toContain("## Verification");
    expect(body).toContain("- Not run.");
    expect(body).toContain("- `.roark/runs/issue/9/readiness.md`");
  });

  test("falls back to the run directory when no artifacts are listed", () => {
    const body = formatPrBody({
      issueNumber: 9,
      runDirRelative: ".roark/runs/issue/9",
      artifactPaths: [],
    });

    expect(body).toContain("- `.roark/runs/issue/9/`");
  });

  test("renders the Attempt section with branch, timestamps, worktree, and metadata path", () => {
    const attemptMetadata = formatAttemptMetadata({
      attempt: 2,
      issueNumber: 10,
      branch: "roark/issue-10",
      baseBranch: "main",
      worktreePath: "/repo",
      runArtifactPath: ".roark/runs/issue/10/attempts/2",
      startedAt: "2026-05-05T07:17:40.000Z",
      endedAt: "2026-05-05T07:42:11.000Z",
      outcome: "published",
    });

    const body = formatPrBody({
      issueNumber: 10,
      verification: okVerification,
      runDirRelative: ".roark/runs/issue/10/attempts/2",
      artifactPaths: [".roark/runs/issue/10/attempts/2/readiness.md"],
      attemptMetadata,
      attemptMetadataPath: ".roark/runs/issue/10/attempts/2/attempt.json",
    });

    expect(body).toContain("## Attempt");
    expect(body).toContain("- Attempt: 2");
    expect(body).toContain("- Branch: `roark/issue-10`");
    expect(body).toContain("- Started: 2026-05-05T07:17:40.000Z");
    expect(body).toContain("- Ended: 2026-05-05T07:42:11.000Z");
    expect(body).toContain("- Worktree: `/repo`");
    expect(body).toContain("- Metadata: `.roark/runs/issue/10/attempts/2/attempt.json`");
    // Attempt block precedes the artifacts list.
    expect(body.indexOf("## Attempt")).toBeLessThan(body.indexOf("## Workflow artifacts"));
    expect(body).toContain("- `.roark/runs/issue/10/attempts/2/readiness.md`");
  });

  test("omits the Attempt section when no metadata is provided", () => {
    const body = formatPrBody({
      issueNumber: 9,
      runDirRelative: ".roark/runs/issue/9",
      artifactPaths: [".roark/runs/issue/9/readiness.md"],
    });
    expect(body).not.toContain("## Attempt");
  });
});
