import type { AutoCliOptions } from "../cli/args.ts";
import { runProcess, runProcessOrThrow } from "../cli/process.ts";
import {
  artifactExists,
  artifactRelativePath,
  finalReviewRef,
  latestFinalReviewPass,
  type WorkflowContext,
} from "../workflow/artifacts.ts";
import type { AutorunBranchPlan } from "./branch.ts";
import type { AutorunIssueCandidate } from "./selection.ts";
import type { VerificationResult } from "./verification.ts";

export const defaultAutorunSuccessLabel = "roark-pr-opened";
export const defaultAutorunRemote = "origin";

export type CommitArgvOptions = { message: string };
export type PushArgvOptions = { remote: string; branchName: string };
export type PrCreateArgvOptions = {
  repo?: string;
  baseBranch: string;
  branchName: string;
  title: string;
  body: string;
};
export type SuccessLabelArgvOptions = {
  repo?: string;
  issueNumber: number;
  label: string;
};

export type FormatPrBodyInput = {
  issueNumber: number;
  verification?: VerificationResult;
  runDirRelative: string;
  artifactPaths: string[];
};

export type PublishAutorunResultInput = {
  options: AutoCliOptions;
  issue: AutorunIssueCandidate;
  branchPlan: AutorunBranchPlan;
  workflowContext: WorkflowContext;
  verification?: VerificationResult;
};

export function buildStageAllArgv(): string[] {
  return ["git", "add", "-A"];
}

export function buildCommitArgv(options: CommitArgvOptions): string[] {
  return ["git", "commit", "-m", options.message];
}

export function buildPushArgv(options: PushArgvOptions): string[] {
  return ["git", "push", "-u", options.remote, options.branchName];
}

export function buildPrCreateArgv(options: PrCreateArgvOptions): string[] {
  const repoArgs = options.repo ? ["--repo", options.repo] : [];
  return [
    "gh",
    "pr",
    "create",
    "--draft",
    "--base",
    options.baseBranch,
    "--head",
    options.branchName,
    "--title",
    options.title,
    "--body",
    options.body,
    ...repoArgs,
  ];
}

export function buildSuccessLabelArgv(options: SuccessLabelArgvOptions): string[] {
  const repoArgs = options.repo ? ["--repo", options.repo] : [];
  return ["gh", "issue", "edit", String(options.issueNumber), "--add-label", options.label, ...repoArgs];
}

export function formatCommitMessage(input: { issueNumber: number }): string {
  return `roark: workflow artifacts for #${input.issueNumber}`;
}

export function formatPrBody(input: FormatPrBodyInput): string {
  const lines: string[] = [];
  lines.push(`Closes #${input.issueNumber}`);
  lines.push("");
  lines.push("## Verification");
  if (input.verification) {
    lines.push(`- Command: \`${input.verification.command}\``);
    lines.push(`- Exit code: ${input.verification.exitCode}`);
    lines.push(`- Status: ${input.verification.ok ? "passed" : "failed"}`);
  } else {
    lines.push("- Not run.");
  }
  lines.push("");
  lines.push("## Workflow artifacts");
  if (input.artifactPaths.length === 0) {
    lines.push(`- \`${input.runDirRelative}/\``);
  } else {
    for (const artifactPath of input.artifactPaths) {
      lines.push(`- \`${artifactPath}\``);
    }
  }
  lines.push("");
  lines.push("Generated by roark autorun.");
  return `${lines.join("\n")}\n`;
}

export function collectPrBodyArtifactPaths(context: WorkflowContext): string[] {
  const candidates: Array<Parameters<typeof artifactRelativePath>[1]> = [
    "issue",
    "triage",
    "implementationPlan",
    "implementationLog",
    "reviewA",
    "reviewB",
    "readiness",
    "verification",
  ];

  const paths = candidates
    .filter((artifact) => artifactExists(context, artifact))
    .map((artifact) => artifactRelativePath(context, artifact));

  const latestFinalReview = latestFinalReviewPass(context);
  if (latestFinalReview !== undefined) {
    paths.push(artifactRelativePath(context, finalReviewRef(latestFinalReview)));
  }

  return paths;
}

export async function hasUncommittedChanges(options: { cwd: string }): Promise<boolean> {
  const result = await runProcess(["git", "status", "--porcelain"], { cwd: options.cwd });
  if (result.exitCode !== 0) {
    throw new Error(
      `git status --porcelain failed with exit code ${result.exitCode}:\n${result.stderr || result.stdout}`,
    );
  }
  return result.stdout.trim() !== "";
}

export async function publishAutorunResult(input: PublishAutorunResultInput): Promise<void> {
  const { options, issue, branchPlan, workflowContext, verification } = input;
  const cwd = options.cwd;

  console.log(`\n=== Publish #${issue.number} ===`);

  if (await hasUncommittedChanges({ cwd })) {
    console.log("- Committing workflow artifacts");
    await runProcessOrThrow(buildStageAllArgv(), { cwd, label: "git add -A" });
    await runProcessOrThrow(
      buildCommitArgv({ message: formatCommitMessage({ issueNumber: issue.number }) }),
      { cwd, label: "git commit" },
    );
  } else {
    console.log("- No uncommitted changes; skipping commit.");
  }

  console.log(`- Pushing ${branchPlan.branchName} to ${options.remote}`);
  await runProcessOrThrow(
    buildPushArgv({ remote: options.remote, branchName: branchPlan.branchName }),
    { cwd, label: `git push ${options.remote}` },
  );

  const body = formatPrBody({
    issueNumber: issue.number,
    verification,
    runDirRelative: workflowContext.runDirRelative,
    artifactPaths: collectPrBodyArtifactPaths(workflowContext),
  });

  console.log("- Creating draft pull request");
  const prStdout = await runProcessOrThrow(
    buildPrCreateArgv({
      repo: options.repo,
      baseBranch: options.baseBranch,
      branchName: branchPlan.branchName,
      title: issue.title,
      body,
    }),
    { cwd, label: "gh pr create --draft" },
  );
  const prUrl = prStdout.trim();
  if (prUrl) console.log(`- Draft PR: ${prUrl}`);

  try {
    await runProcessOrThrow(
      buildSuccessLabelArgv({ repo: options.repo, issueNumber: issue.number, label: options.successLabel }),
      { cwd, label: "gh issue edit --add-label (success)" },
    );
  } catch (error) {
    console.warn(
      `Failed to apply success label '${options.successLabel}': ${error instanceof Error ? error.message : String(error)}`,
    );
  }
}
