import type { AutoCliOptions } from "../cli/args.ts";
import { readFileSync } from "node:fs";
import { runProcess, runProcessOrThrow } from "../cli/process.ts";
import { buildRemoveLabelArgv } from "./failure.ts";
import {
  artifactExists,
  artifactPath,
  artifactRelativePath,
  finalReviewRef,
  latestFinalReviewPass,
  type WorkflowContext,
} from "../workflow/artifacts.ts";
import type { AttemptMetadata } from "./attempts.ts";
import type { AutorunBranchPlan } from "./branch.ts";
import type { AutorunIssueCandidate } from "./selection.ts";
import type { VerificationResult } from "./verification.ts";
import { parseVerdict } from "../workflow/verdicts.ts";

export const defaultAutorunSuccessLabel = "roark-pr-opened";
export const defaultAutorunRemote = "origin";

export type CommitArgvOptions = { message: string };
export type PushArgvOptions = { remote: string; branchName: string };
export type PrCreateArgvOptions = {
  repo?: string;
  baseBranch: string;
  branchName: string;
  title: string;
  body: string;
};
export type SuccessLabelArgvOptions = {
  repo?: string;
  issueNumber: number;
  label: string;
};

export type ReviewVerdictSummary = {
  reviewA?: string;
  reviewB?: string;
};

export type FormatPrBodyInput = {
  issueNumber: number;
  verification?: VerificationResult;
  runDirRelative: string;
  artifactPaths: string[];
  attemptMetadata?: AttemptMetadata;
  attemptMetadataPath?: string;
  reviewVerdicts?: ReviewVerdictSummary;
};

export type AutorunPublishOptions = Pick<
  AutoCliOptions,
  "cwd" | "repo" | "failureLabel" | "successLabel" | "inProgressLabel" | "remote" | "baseBranch"
>;

export type PublishAutorunResultInput = {
  options: AutorunPublishOptions;
  issue: AutorunIssueCandidate;
  branchPlan: AutorunBranchPlan;
  workflowContext: WorkflowContext;
  verification?: VerificationResult;
  attemptMetadata?: AttemptMetadata;
  attemptMetadataPath?: string;
};

export function buildStageAllArgv(): string[] {
  return ["git", "add", "-A"];
}

export function buildCommitArgv(options: CommitArgvOptions): string[] {
  return ["git", "commit", "-m", options.message];
}

export function buildPushArgv(options: PushArgvOptions): string[] {
  return ["git", "push", "-u", options.remote, options.branchName];
}

export function buildPrCreateArgv(options: PrCreateArgvOptions): string[] {
  const repoArgs = options.repo ? ["--repo", options.repo] : [];
  return [
    "gh",
    "pr",
    "create",
    "--draft",
    "--base",
    options.baseBranch,
    "--head",
    options.branchName,
    "--title",
    options.title,
    "--body",
    options.body,
    ...repoArgs,
  ];
}

export function buildSuccessLabelArgv(options: SuccessLabelArgvOptions): string[] {
  const repoArgs = options.repo ? ["--repo", options.repo] : [];
  return ["gh", "issue", "edit", String(options.issueNumber), "--add-label", options.label, ...repoArgs];
}

export function formatCommitMessage(input: { issueNumber: number }): string {
  return `roark: implement issue #${input.issueNumber}`;
}

export function formatPrBody(input: FormatPrBodyInput): string {
  const lines: string[] = [];
  lines.push(`Closes #${input.issueNumber}`);
  lines.push("");
  lines.push("## Verification");
  if (input.verification) {
    lines.push(`- Command: \`${input.verification.command}\``);
    lines.push(`- Exit code: ${input.verification.exitCode}`);
    lines.push(`- Status: ${input.verification.ok ? "passed" : "failed"}`);
  } else {
    lines.push("- Not run.");
  }
  lines.push("");
  if (input.attemptMetadata) {
    const meta = input.attemptMetadata;
    lines.push("## Attempt");
    lines.push(`- Attempt: ${meta.attempt}`);
    lines.push(`- Branch: \`${meta.branch}\``);
    lines.push(`- Started: ${meta.startedAt}`);
    if (meta.endedAt) lines.push(`- Ended: ${meta.endedAt}`);
    lines.push(`- Worktree: \`${meta.worktreePath}\``);
    if (input.attemptMetadataPath) {
      lines.push(`- Metadata: \`${input.attemptMetadataPath}\``);
    }
    lines.push("");
  }
  lines.push("## Review summary");
  lines.push(`- Review A: ${input.reviewVerdicts?.reviewA ?? "unknown"}`);
  lines.push(`- Review B: ${input.reviewVerdicts?.reviewB ?? "unknown"}`);
  lines.push(`- Full run ledger: issue comments on #${input.issueNumber}`);
  lines.push("");
  lines.push("## Workflow artifacts");
  lines.push("These artifacts are local control-plane state and are not committed to this PR branch.");
  if (input.artifactPaths.length === 0) {
    lines.push(`- \`${input.runDirRelative}/\``);
  } else {
    for (const artifactPath of input.artifactPaths) {
      lines.push(`- \`${artifactPath}\``);
    }
  }
  lines.push("");
  lines.push("Generated by roark autorun.");
  return `${lines.join("\n")}\n`;
}

export function collectPrBodyArtifactPaths(context: WorkflowContext): string[] {
  const candidates: Array<Parameters<typeof artifactRelativePath>[1]> = [
    "issue",
    "triage",
    "implementationPlan",
    "implementationLog",
    "reviewA",
    "reviewB",
    "readiness",
    "verification",
  ];

  const paths = candidates
    .filter((artifact) => artifactExists(context, artifact))
    .map((artifact) => artifactRelativePath(context, artifact));

  const latestFinalReview = latestFinalReviewPass(context);
  if (latestFinalReview !== undefined) {
    paths.push(artifactRelativePath(context, finalReviewRef(latestFinalReview)));
  }

  return paths;
}

export async function hasUncommittedChanges(options: { cwd: string }): Promise<boolean> {
  const result = await runProcess(["git", "status", "--porcelain"], { cwd: options.cwd });
  if (result.exitCode !== 0) {
    throw new Error(
      `git status --porcelain failed with exit code ${result.exitCode}:\n${result.stderr || result.stdout}`,
    );
  }
  return result.stdout.trim() !== "";
}

export async function publishAutorunResult(input: PublishAutorunResultInput): Promise<string | undefined> {
  const { options, issue, branchPlan, workflowContext, verification, attemptMetadata, attemptMetadataPath } = input;
  const agentCwd = workflowContext.agentCwd;
  const controlCwd = workflowContext.controlCwd;

  console.log(`\n=== Publish #${issue.number} ===`);

  if (await hasUncommittedChanges({ cwd: agentCwd })) {
    console.log("- Committing worktree changes");
    await runProcessOrThrow(buildStageAllArgv(), { cwd: agentCwd, label: "git add -A" });
    await runProcessOrThrow(
      buildCommitArgv({ message: formatCommitMessage({ issueNumber: issue.number }) }),
      { cwd: agentCwd, label: "git commit" },
    );
  } else {
    console.log("- No uncommitted changes; skipping commit.");
  }

  console.log(`- Pushing ${branchPlan.branchName} to ${options.remote}`);
  await runProcessOrThrow(
    buildPushArgv({ remote: options.remote, branchName: branchPlan.branchName }),
    { cwd: agentCwd, label: `git push ${options.remote}` },
  );

  const body = formatPrBody({
    issueNumber: issue.number,
    verification,
    runDirRelative: workflowContext.runDirRelative,
    artifactPaths: collectPrBodyArtifactPaths(workflowContext),
    attemptMetadata,
    attemptMetadataPath,
    reviewVerdicts: collectReviewVerdicts(workflowContext),
  });

  console.log("- Creating draft pull request");
  const prStdout = await runProcessOrThrow(
    buildPrCreateArgv({
      repo: options.repo,
      baseBranch: options.baseBranch,
      branchName: branchPlan.branchName,
      title: issue.title,
      body,
    }),
    { cwd: agentCwd, label: "gh pr create --draft" },
  );
  const prUrl = prStdout.trim();
  if (prUrl) console.log(`- Draft PR: ${prUrl}`);

  try {
    await runProcessOrThrow(
      buildSuccessLabelArgv({ repo: options.repo, issueNumber: issue.number, label: options.successLabel }),
      { cwd: controlCwd, label: "gh issue edit --add-label (success)" },
    );
  } catch (error) {
    console.warn(
      `Failed to apply success label '${options.successLabel}': ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  for (const label of [options.inProgressLabel, options.failureLabel].filter((label) => label !== options.successLabel)) {
    try {
      await runProcessOrThrow(
        buildRemoveLabelArgv({ repo: options.repo, issueNumber: issue.number, label }),
        { cwd: controlCwd, label: "gh issue edit --remove-label (success cleanup)" },
      );
    } catch (error) {
      console.warn(
        `Failed to remove label '${label}': ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  return prUrl || undefined;
}

export function collectReviewVerdicts(context: WorkflowContext): ReviewVerdictSummary {
  return {
    reviewA: readVerdictIfExists(context, "reviewA"),
    reviewB: readVerdictIfExists(context, "reviewB"),
  };
}

function readVerdictIfExists(context: WorkflowContext, artifact: "reviewA" | "reviewB"): string | undefined {
  if (!artifactExists(context, artifact)) return undefined;
  try {
    return parseVerdict(readFileSync(artifactPath(context, artifact), "utf8")) ?? "unknown";
  } catch {
    return undefined;
  }
}
